### PR TITLE
Add layer properties

### PR DESCRIPTION
**Pull request by 1e4**
Added layer properties.

Reason why I'm committing to the old repo is because I still can't get tiled to export as JSON on Linux

### CODE REVIEW

**Comment by 1e4** [comment]
Time to just support PHP 7?

**Comment by martinlindhe** [comment]
Thanks for adding this.

The tests should be fixed by declaring

`"properties":null`  after this line

https://github.com/martinlindhe/php-tiled-tmx/blob/master/test/JsonMapWriterTest.php#L35

There is no reason to drop support for old php versions as this code perfectly works from php 5.4

**Comment by 1e4** [comment]
Other than HHVM, all are now passing

**Comment by martinlindhe** [comment]
Thanks, good enough :-)

**Pull request merged**
